local M = {}

function M.get(c, config)
  return {
    -- Telescope
    TelescopeNormal = { fg = c.fg, bg = c.bg_dark },
    TelescopeBorder = { fg = c.border_light, bg = c.bg_dark },
    TelescopeTitle = { fg = c.green, bold = true },
    TelescopePromptNormal = { fg = c.fg, bg = c.bg_highlight },
    TelescopePromptBorder = { fg = c.bg_highlight, bg = c.bg_highlight },
    TelescopePromptTitle = { fg = c.bg, bg = c.green, bold = true },
    TelescopePromptPrefix = { fg = c.green },
    TelescopePromptCounter = { fg = c.gray },
    TelescopePreviewNormal = { fg = c.fg, bg = c.bg_dark },
    TelescopePreviewBorder = { fg = c.border_light, bg = c.bg_dark },
    TelescopePreviewTitle = { fg = c.bg, bg = c.blue, bold = true },
    TelescopePreviewLine = { bg = c.bg_highlight },
    TelescopeResultsNormal = { fg = c.fg, bg = c.bg_dark },
    TelescopeResultsBorder = { fg = c.border_light, bg = c.bg_dark },
    TelescopeResultsTitle = { fg = c.bg_dark, bg = c.bg_dark },
    TelescopeSelection = { fg = c.fg, bg = c.bg_highlight },
    TelescopeSelectionCaret = { fg = c.green, bg = c.bg_highlight },
    TelescopeMultiSelection = { fg = c.purple, bg = c.bg_highlight },
    TelescopeMultiIcon = { fg = c.purple },
    TelescopeMatching = { fg = c.green, bold = true },

    -- Neo-tree
    NeoTreeNormal = { fg = c.fg, bg = c.bg_dark },
    NeoTreeNormalNC = { fg = c.fg, bg = c.bg_dark },
    NeoTreeVertSplit = { fg = c.bg_dark, bg = c.bg_dark },
    NeoTreeWinSeparator = { fg = c.bg_dark, bg = c.bg_dark },
    NeoTreeEndOfBuffer = { fg = "#13171b" },
    NeoTreeRootName = { fg = c.fg, bold = true },
    NeoTreeFileName = { fg = c.fg },
    NeoTreeFileIcon = { fg = c.blue },
    NeoTreeDirectoryName = { fg = c.blue },
    NeoTreeDirectoryIcon = { fg = c.blue },
    NeoTreeSymbolicLinkTarget = { fg = c.aqua },
    NeoTreeExpander = { fg = c.gray_dark },
    NeoTreeIndentMarker = { fg = c.bg_light },
    NeoTreeGitAdded = { fg = c.git_add },
    NeoTreeGitConflict = { fg = c.git_conflict },
    NeoTreeGitDeleted = { fg = c.git_delete },
    NeoTreeGitIgnored = { fg = c.git_ignored },
    NeoTreeGitModified = { fg = c.git_change },
    NeoTreeGitUnstaged = { fg = c.git_change },
    NeoTreeGitUntracked = { fg = c.git_untracked },
    NeoTreeGitStaged = { fg = c.green },
    NeoTreeFloatBorder = { fg = c.border_light },
    NeoTreeFloatTitle = { fg = c.green, bold = true },
    NeoTreeTitleBar = { fg = c.bg, bg = c.green },
    NeoTreeCursorLine = { bg = c.bg_highlight },
    NeoTreeDimText = { fg = c.gray_dark },
    NeoTreeDotfile = { fg = c.gray },
    NeoTreeHiddenByName = { fg = c.gray },
    NeoTreeFilterTerm = { fg = c.green, bold = true },
    NeoTreeMessage = { fg = c.gray, italic = true },
    NeoTreeModified = { fg = c.git_change },
    NeoTreePreview = { bg = c.bg_highlight },
    NeoTreeTabActive = { fg = c.fg, bg = c.bg, bold = true },
    NeoTreeTabInactive = { fg = c.gray, bg = c.bg_light },
    NeoTreeTabSeparatorActive = { fg = c.green, bg = c.bg },
    NeoTreeTabSeparatorInactive = { fg = c.bg_light, bg = c.bg_light },

    -- Gitsigns
    GitSignsAdd = { fg = c.git_add },
    GitSignsChange = { fg = c.yellow },
    GitSignsDelete = { fg = c.git_delete },
    GitSignsAddNr = { fg = c.git_add },
    GitSignsChangeNr = { fg = c.yellow },
    GitSignsDeleteNr = { fg = c.git_delete },
    GitSignsAddLn = { bg = c.diff_add_bg },
    GitSignsChangeLn = { bg = c.diff_change_bg },
    GitSignsDeleteLn = { bg = c.diff_delete_bg },
    GitSignsAddInline = { fg = c.git_add, bg = "#2d5540" },
    GitSignsChangeInline = { fg = c.yellow, bg = "#4a4a2d" },
    GitSignsDeleteInline = { fg = c.git_delete, bg = "#552d30" },
    GitSignsAddLnInline = { fg = c.git_add, bg = "#2d5540" },
    GitSignsChangeLnInline = { fg = c.yellow, bg = "#4a4a2d" },
    GitSignsDeleteLnInline = { fg = c.git_delete, bg = "#552d30" },
    GitSignsDeleteVirtLn = { fg = c.git_delete, bg = c.diff_delete_bg },
    GitSignsDeleteVirtLnInline = { fg = c.git_delete, bg = "#552d30" },
    GitSignsCurrentLineBlame = { fg = c.gray_dark, italic = true },
    GitSignsAddPreview = { fg = c.git_add },
    GitSignsDeletePreview = { fg = c.git_delete },
    GitSignsStagedAdd = { fg = c.git_staged_add },
    GitSignsStagedChange = { fg = c.git_staged_mod },
    GitSignsStagedDelete = { fg = c.git_staged_del },
    GitSignsStagedAddNr = { fg = c.git_staged_add },
    GitSignsStagedChangeNr = { fg = c.git_staged_mod },
    GitSignsStagedDeleteNr = { fg = c.git_staged_del },
    GitSignsStagedAddLn = { bg = "#1a3025" },
    GitSignsStagedChangeLn = { bg = "#2a2820" },
    GitSignsStagedDeleteLn = { bg = "#2d1a1c" },

    -- Which-key
    WhichKey = { fg = c.sky },
    WhichKeyGroup = { fg = c.purple },
    WhichKeySeparator = { fg = c.gray_dark },
    WhichKeyDesc = { fg = c.fg },
    WhichKeyValue = { fg = c.gray },
    WhichKeyFloat = { bg = c.bg_dark },
    WhichKeyBorder = { fg = c.border_light, bg = c.bg_dark },
    WhichKeyNormal = { bg = c.bg_dark },

    -- Mini
    MiniStatuslineDevinfo = { fg = c.fg, bg = c.bg_highlight },
    MiniStatuslineFileinfo = { fg = c.fg, bg = c.bg_highlight },
    MiniStatuslineFilename = { fg = c.fg, bg = c.bg_light },
    MiniStatuslineInactive = { fg = c.gray_dark, bg = c.bg_light },
    MiniStatuslineModeCommand = { fg = c.bg, bg = c.yellow, bold = true },
    MiniStatuslineModeInsert = { fg = c.bg, bg = c.green, bold = true },
    MiniStatuslineModeNormal = { fg = c.bg, bg = c.blue, bold = true },
    MiniStatuslineModeOther = { fg = c.bg, bg = c.teal, bold = true },
    MiniStatuslineModeReplace = { fg = c.bg, bg = c.red, bold = true },
    MiniStatuslineModeVisual = { fg = c.bg, bg = c.purple, bold = true },
    MiniTablineCurrent = { fg = c.fg, bg = c.bg, bold = true },
    MiniTablineFill = { bg = c.bg_light },
    MiniTablineHidden = { fg = c.gray, bg = c.bg_light },
    MiniTablineModifiedCurrent = { fg = c.git_change, bg = c.bg, bold = true },
    MiniTablineModifiedHidden = { fg = c.git_change, bg = c.bg_light },
    MiniTablineModifiedVisible = { fg = c.git_change, bg = c.bg_light },
    MiniTablineTabpagesection = { fg = c.fg, bg = c.bg_highlight },
    MiniTablineVisible = { fg = c.fg, bg = c.bg_light },
    MiniIndentscopeSymbol = { fg = c.blue },
    MiniIndentscopeSymbolOff = { fg = c.gray_dark },
    MiniCursorword = { bg = c.word_highlight },
    MiniCursorwordCurrent = { bg = c.word_highlight },
    MiniSurround = { fg = c.bg, bg = c.orange },
    MiniJump = { fg = c.bg, bg = c.yellow, bold = true },
    MiniJump2dSpot = { fg = c.red, bold = true },
    MiniJump2dSpotAhead = { fg = c.teal },
    MiniJump2dSpotUnique = { fg = c.orange, bold = true },
    MiniFilesDirectory = { fg = c.blue },
    MiniFilesFile = { fg = c.fg },
    MiniFilesNormal = { fg = c.fg, bg = c.bg_dark },
    MiniFilesBorder = { fg = c.border_light, bg = c.bg_dark },
    MiniFilesCursorLine = { bg = c.bg_highlight },
    MiniFilesTitle = { fg = c.green, bold = true },
    MiniFilesTitleFocused = { fg = c.green, bold = true },
    MiniPickBorder = { fg = c.border_light, bg = c.bg_dark },
    MiniPickBorderBusy = { fg = c.yellow },
    MiniPickBorderText = { fg = c.green, bold = true },
    MiniPickIconDirectory = { fg = c.blue },
    MiniPickIconFile = { fg = c.fg },
    MiniPickHeader = { fg = c.purple },
    MiniPickMatchCurrent = { bg = c.bg_highlight },
    MiniPickMatchMarked = { bg = c.bg_visual },
    MiniPickMatchRanges = { fg = c.green, bold = true },
    MiniPickNormal = { fg = c.fg, bg = c.bg_dark },
    MiniPickPreviewLine = { bg = c.bg_highlight },
    MiniPickPreviewRegion = { bg = c.bg_visual },
    MiniPickPrompt = { fg = c.green },

    -- Indent-blankline
    IblIndent = { fg = c.indent_guide },
    IblScope = { fg = c.indent_guide_active },
    IblWhitespace = { fg = c.whitespace },
    IndentBlanklineChar = { fg = c.indent_guide },
    IndentBlanklineContextChar = { fg = c.indent_guide_active },
    IndentBlanklineContextStart = { sp = c.indent_guide_active, underline = true },
    IndentBlanklineSpaceChar = { fg = c.whitespace },
    IndentBlanklineSpaceCharBlankline = { fg = c.whitespace },

    -- Blink.cmp
    BlinkCmpMenu = { fg = c.fg, bg = c.bg_dark },
    BlinkCmpMenuBorder = { fg = c.border_light, bg = c.bg_dark },
    BlinkCmpMenuSelection = { bg = c.pmenu_sel },
    BlinkCmpScrollBarThumb = { bg = c.gray_dark },
    BlinkCmpScrollBarGutter = { bg = c.bg_dark },
    BlinkCmpLabel = { fg = c.fg },
    BlinkCmpLabelDeprecated = { fg = c.gray, strikethrough = true },
    BlinkCmpLabelMatch = { fg = c.pmenu_match, bold = true },
    BlinkCmpLabelDetail = { fg = c.gray },
    BlinkCmpLabelDescription = { fg = c.gray },
    BlinkCmpKind = { fg = c.purple },
    BlinkCmpKindClass = { fg = c.yellow },
    BlinkCmpKindColor = { fg = c.orange },
    BlinkCmpKindConstant = { fg = c.orange },
    BlinkCmpKindConstructor = { fg = c.yellow },
    BlinkCmpKindEnum = { fg = c.yellow },
    BlinkCmpKindEnumMember = { fg = c.teal },
    BlinkCmpKindEvent = { fg = c.orange },
    BlinkCmpKindField = { fg = c.cyan },
    BlinkCmpKindFile = { fg = c.fg },
    BlinkCmpKindFolder = { fg = c.blue },
    BlinkCmpKindFunction = { fg = c.sky },
    BlinkCmpKindInterface = { fg = c.yellow },
    BlinkCmpKindKeyword = { fg = c.purple },
    BlinkCmpKindMethod = { fg = c.sky },
    BlinkCmpKindModule = { fg = c.fg },
    BlinkCmpKindOperator = { fg = c.fg },
    BlinkCmpKindProperty = { fg = c.cyan },
    BlinkCmpKindReference = { fg = c.blue },
    BlinkCmpKindSnippet = { fg = c.teal },
    BlinkCmpKindStruct = { fg = c.yellow },
    BlinkCmpKindText = { fg = c.fg },
    BlinkCmpKindTypeParameter = { fg = c.yellow },
    BlinkCmpKindUnit = { fg = c.blue },
    BlinkCmpKindValue = { fg = c.orange },
    BlinkCmpKindVariable = { fg = c.blue },
    BlinkCmpSource = { fg = c.gray },
    BlinkCmpGhostText = { fg = c.gray_dark },
    BlinkCmpDoc = { fg = c.fg, bg = c.bg },
    BlinkCmpDocBorder = { fg = c.border_light, bg = c.bg },
    BlinkCmpDocCursorLine = { bg = c.bg_highlight },
    BlinkCmpSignatureHelp = { fg = c.fg, bg = c.bg },
    BlinkCmpSignatureHelpBorder = { fg = c.border_light, bg = c.bg },
    BlinkCmpSignatureHelpActiveParameter = { fg = c.orange, bold = true },

    -- nvim-cmp
    CmpItemAbbrMatch = { fg = c.pmenu_match, bold = true },
    CmpItemAbbrMatchFuzzy = { fg = c.pmenu_match, bold = true },
    CmpItemAbbrDeprecated = { fg = c.gray, strikethrough = true },
    CmpItemMenu = { fg = c.gray },
    CmpItemKindClass = { fg = c.yellow },
    CmpItemKindColor = { fg = c.orange },
    CmpItemKindConstant = { fg = c.orange },
    CmpItemKindConstructor = { fg = c.yellow },
    CmpItemKindEnum = { fg = c.yellow },
    CmpItemKindEnumMember = { fg = c.teal },
    CmpItemKindEvent = { fg = c.orange },
    CmpItemKindField = { fg = c.cyan },
    CmpItemKindFile = { fg = c.fg },
    CmpItemKindFolder = { fg = c.blue },
    CmpItemKindFunction = { fg = c.sky },
    CmpItemKindInterface = { fg = c.yellow },
    CmpItemKindKeyword = { fg = c.purple },
    CmpItemKindMethod = { fg = c.sky },
    CmpItemKindModule = { fg = c.fg },
    CmpItemKindOperator = { fg = c.fg },
    CmpItemKindProperty = { fg = c.cyan },
    CmpItemKindReference = { fg = c.blue },
    CmpItemKindSnippet = { fg = c.teal },
    CmpItemKindStruct = { fg = c.yellow },
    CmpItemKindText = { fg = c.fg },
    CmpItemKindTypeParameter = { fg = c.yellow },
    CmpItemKindUnit = { fg = c.blue },
    CmpItemKindValue = { fg = c.orange },
    CmpItemKindVariable = { fg = c.blue },

    -- Flash
    FlashBackdrop = { fg = c.gray_dark },
    FlashMatch = { fg = c.fg, bg = c.bg_visual },
    FlashCurrent = { fg = c.bg, bg = c.green },
    FlashLabel = { fg = c.bg, bg = c.red, bold = true },

    -- Trouble
    TroubleNormal = { fg = c.fg, bg = c.bg_dark },
    TroubleText = { fg = c.fg },
    TroubleCount = { fg = c.purple, bg = c.bg_highlight },
    TroubleError = { fg = c.error },
    TroubleWarning = { fg = c.warning },
    TroubleInformation = { fg = c.info },
    TroubleHint = { fg = c.hint },
    TroubleLocation = { fg = c.gray },
    TroubleFile = { fg = c.blue },
    TroubleFoldIcon = { fg = c.gray_dark },
    TroubleIndent = { fg = c.indent_guide },
    TroubleCode = { fg = c.gray },
    TroubleSource = { fg = c.gray, italic = true },

    -- Todo-comments
    TodoBgFIX = { fg = c.bg, bg = c.red, bold = true },
    TodoBgHACK = { fg = c.bg, bg = c.orange, bold = true },
    TodoBgNOTE = { fg = c.bg, bg = c.info, bold = true },
    TodoBgPERF = { fg = c.bg, bg = c.purple, bold = true },
    TodoBgTODO = { fg = c.bg, bg = c.yellow, bold = true },
    TodoBgWARN = { fg = c.bg, bg = c.warning, bold = true },
    TodoFgFIX = { fg = c.red },
    TodoFgHACK = { fg = c.orange },
    TodoFgNOTE = { fg = c.info },
    TodoFgPERF = { fg = c.purple },
    TodoFgTODO = { fg = c.yellow },
    TodoFgWARN = { fg = c.warning },
    TodoSignFIX = { fg = c.red },
    TodoSignHACK = { fg = c.orange },
    TodoSignNOTE = { fg = c.info },
    TodoSignPERF = { fg = c.purple },
    TodoSignTODO = { fg = c.yellow },
    TodoSignWARN = { fg = c.warning },

    -- Dashboard / Alpha
    DashboardShortCut = { fg = c.teal },
    DashboardHeader = { fg = c.blue },
    DashboardCenter = { fg = c.purple },
    DashboardFooter = { fg = c.gray, italic = true },
    DashboardKey = { fg = c.orange },
    DashboardDesc = { fg = c.fg },
    DashboardIcon = { fg = c.blue },
    AlphaNormal = { fg = c.fg, bg = c.bg_dark },
    AlphaShortcut = { fg = c.teal, bg = c.bg_dark },
    AlphaHeader = { fg = c.green, bg = c.bg_dark },
    AlphaHeaderLabel = { fg = c.orange, bg = c.bg_dark },
    AlphaFooter = { fg = c.gray, bg = c.bg_dark, italic = true },
    AlphaButtons = { fg = c.purple, bg = c.bg_dark },

    -- nvim-tree
    NvimTreeNormal = { fg = c.fg, bg = c.bg_dark },
    NvimTreeNormalNC = { fg = c.fg, bg = c.bg_dark },
    NvimTreeRootFolder = { fg = c.fg, bold = true },
    NvimTreeFolderName = { fg = c.blue },
    NvimTreeFolderIcon = { fg = c.blue },
    NvimTreeOpenedFolderName = { fg = c.blue },
    NvimTreeEmptyFolderName = { fg = c.gray },
    NvimTreeSymlink = { fg = c.aqua },
    NvimTreeSpecialFile = { fg = c.purple },
    NvimTreeImageFile = { fg = c.fg },
    NvimTreeOpenedFile = { fg = c.green },
    NvimTreeGitDirty = { fg = c.git_change },
    NvimTreeGitNew = { fg = c.git_untracked },
    NvimTreeGitDeleted = { fg = c.git_delete },
    NvimTreeGitStaged = { fg = c.green },
    NvimTreeIndentMarker = { fg = c.indent_guide },
    NvimTreeWinSeparator = { fg = c.bg_dark, bg = c.bg_dark },

    -- Bufferline
    BufferLineFill = { bg = c.bg_light },
    BufferLineBackground = { fg = c.fg, bg = c.bg_light },
    BufferLineBufferVisible = { fg = c.fg, bg = c.bg_light },
    BufferLineBufferSelected = { fg = c.fg, bg = c.bg, bold = true },
    BufferLineTab = { fg = c.gray, bg = c.bg_light },
    BufferLineTabSelected = { fg = c.fg, bg = c.bg },
    BufferLineTabSeparator = { fg = c.bg_light, bg = c.bg_light },
    BufferLineTabSeparatorSelected = { fg = c.bg, bg = c.bg },
    BufferLineSeparator = { fg = c.bg_light, bg = c.bg_light },
    BufferLineSeparatorVisible = { fg = c.bg_light, bg = c.bg_light },
    BufferLineSeparatorSelected = { fg = c.bg, bg = c.bg },
    BufferLineIndicatorSelected = { fg = c.border_active },
    BufferLineIndicatorVisible = { fg = c.bg_light },
    BufferLineModified = { fg = c.git_change },
    BufferLineModifiedSelected = { fg = c.git_change },
    BufferLineModifiedVisible = { fg = c.git_change },
    BufferLineCloseButton = { fg = c.gray },
    BufferLineCloseButtonSelected = { fg = c.red },
    BufferLineCloseButtonVisible = { fg = c.gray },

    -- Lualine
    lualine_a_normal = { fg = c.bg, bg = c.blue, bold = true },
    lualine_a_insert = { fg = c.bg, bg = c.green, bold = true },
    lualine_a_visual = { fg = c.bg, bg = c.purple, bold = true },
    lualine_a_replace = { fg = c.bg, bg = c.red, bold = true },
    lualine_a_command = { fg = c.bg, bg = c.yellow, bold = true },
    lualine_b_normal = { fg = c.fg, bg = c.bg_highlight },
    lualine_c_normal = { fg = c.fg, bg = c.bg_light },

    -- ToggleTerm
    ToggleTerm = { bg = c.bg_dark },
    ToggleTermNormal = { fg = c.fg, bg = c.bg_dark },
    ToggleTermNormalFloat = { fg = c.fg, bg = c.bg_dark },
    ToggleTermFloatBorder = { fg = c.border_light, bg = c.bg_dark },

    -- Mason
    MasonNormal = { fg = c.fg, bg = c.bg_dark },
    MasonHeader = { fg = c.bg, bg = c.green, bold = true },
    MasonHeaderSecondary = { fg = c.bg, bg = c.blue, bold = true },
    MasonHighlight = { fg = c.green },
    MasonHighlightBlock = { fg = c.bg, bg = c.green },
    MasonHighlightBlockBold = { fg = c.bg, bg = c.green, bold = true },
    MasonHighlightSecondary = { fg = c.blue },
    MasonHighlightBlockSecondary = { fg = c.bg, bg = c.blue },
    MasonMuted = { fg = c.gray },
    MasonMutedBlock = { fg = c.bg, bg = c.gray },
    MasonError = { fg = c.error },

    -- Lazy
    LazyButton = { fg = c.fg, bg = c.bg_highlight },
    LazyButtonActive = { fg = c.fg_light, bg = c.pmenu_sel, bold = true },
    LazyComment = { fg = c.gray },
    LazyCommit = { fg = c.teal },
    LazyCommitIssue = { fg = c.orange },
    LazyCommitScope = { fg = c.gray, italic = true },
    LazyCommitType = { fg = c.purple },
    LazyDimmed = { fg = c.gray_dark },
    LazyDir = { fg = c.blue },
    LazyH1 = { fg = c.bg, bg = c.green, bold = true },
    LazyH2 = { fg = c.blue, bold = true },
    LazyLocal = { fg = c.orange },
    LazyNoCond = { fg = c.red },
    LazyNormal = { fg = c.fg, bg = c.bg_dark },
    LazyProp = { fg = c.cyan },
    LazyReasonCmd = { fg = c.yellow },
    LazyReasonEvent = { fg = c.orange },
    LazyReasonFt = { fg = c.teal },
    LazyReasonImport = { fg = c.purple },
    LazyReasonKeys = { fg = c.blue },
    LazyReasonPlugin = { fg = c.green },
    LazyReasonRuntime = { fg = c.gray },
    LazyReasonSource = { fg = c.gray },
    LazyReasonStart = { fg = c.green },
    LazySpecial = { fg = c.green },
    LazyTaskError = { fg = c.error },
    LazyTaskOutput = { fg = c.fg },
    LazyUrl = { fg = c.link, underline = true },
    LazyValue = { fg = c.green },

    -- Hlargs
    Hlargs = { fg = c.teal, italic = true },

    -- FZF-lua
    FzfLuaNormal = { fg = c.fg, bg = c.bg_dark },
    FzfLuaBorder = { fg = c.border_light, bg = c.bg_dark },
    FzfLuaTitle = { fg = c.green, bold = true },
    FzfLuaPreviewNormal = { fg = c.fg, bg = c.bg_dark },
    FzfLuaPreviewBorder = { fg = c.border_light, bg = c.bg_dark },
    FzfLuaPreviewTitle = { fg = c.blue, bold = true },
    FzfLuaCursor = { fg = c.bg, bg = c.green },
    FzfLuaCursorLine = { bg = c.bg_highlight },
    FzfLuaCursorLineNr = { fg = c.line_nr_active, bold = true },
    FzfLuaSearch = { fg = c.bg, bg = c.green },
    FzfLuaScrollBorderEmpty = { fg = c.bg_highlight },
    FzfLuaScrollBorderFull = { fg = c.green },
    FzfLuaScrollFloatEmpty = { bg = c.bg_highlight },
    FzfLuaScrollFloatFull = { bg = c.green },
    FzfLuaHelpNormal = { fg = c.fg, bg = c.bg_dark },
    FzfLuaHelpBorder = { fg = c.border_light, bg = c.bg_dark },
    FzfLuaHeaderBind = { fg = c.blue },
    FzfLuaHeaderText = { fg = c.purple },
    FzfLuaPathColNr = { fg = c.yellow },
    FzfLuaPathLineNr = { fg = c.green },
    FzfLuaBufName = { fg = c.purple },
    FzfLuaBufNr = { fg = c.yellow },
    FzfLuaBufFlagCur = { fg = c.green },
    FzfLuaBufFlagAlt = { fg = c.blue },
    FzfLuaTabTitle = { fg = c.green, bold = true },
    FzfLuaTabMarker = { fg = c.green },
    FzfLuaLiveSym = { fg = c.yellow },

    -- Diffview
    DiffviewNormal = { fg = c.fg, bg = c.bg_dark },
    DiffviewFilePanelTitle = { fg = c.blue, bold = true },
    DiffviewFilePanelCounter = { fg = c.purple },
    DiffviewFilePanelFileName = { fg = c.fg },
    DiffviewFilePanelPath = { fg = c.gray },
    DiffviewFilePanelRootPath = { fg = c.gray },
    DiffviewFilePanelInsertions = { fg = c.git_add },
    DiffviewFilePanelDeletions = { fg = c.git_delete },
    DiffviewFilePanelConflicts = { fg = c.git_conflict },
    DiffviewFolderName = { fg = c.blue },
    DiffviewFolderSign = { fg = c.blue },
    DiffviewStatusLine = { fg = c.fg, bg = c.bg_light },
    DiffviewStatusLineNC = { fg = c.fg_dark, bg = c.bg_dark },
    DiffviewStatusAdded = { fg = c.git_add },
    DiffviewStatusModified = { fg = c.git_change },
    DiffviewStatusRenamed = { fg = c.aqua },
    DiffviewStatusCopied = { fg = c.aqua },
    DiffviewStatusTypeChange = { fg = c.yellow },
    DiffviewStatusUnmerged = { fg = c.git_conflict },
    DiffviewStatusUnknown = { fg = c.gray },
    DiffviewStatusDeleted = { fg = c.git_delete },
    DiffviewStatusBroken = { fg = c.error },
    DiffviewStatusIgnored = { fg = c.git_ignored },
    DiffviewDim1 = { fg = c.gray },
    DiffviewReference = { fg = c.purple },
    DiffviewPrimary = { fg = c.blue },
    DiffviewSecondary = { fg = c.green },
    DiffviewDiffAdd = { bg = c.diff_add_bg },
    DiffviewDiffAddAsDelete = { bg = c.diff_delete_bg },
    DiffviewDiffChange = { bg = c.diff_change_bg },
    DiffviewDiffDelete = { bg = c.diff_delete_bg },
    DiffviewDiffText = { bg = c.diff_text_bg },
    DiffviewDiffAddText = { bg = "#2d5540" },
    DiffviewDiffDeleteText = { bg = "#552d30" },

    -- Neogit
    NeogitBranch = { fg = c.purple },
    NeogitRemote = { fg = c.green },
    NeogitHunkHeader = { fg = c.fg, bg = c.bg_highlight },
    NeogitHunkHeaderHighlight = { fg = c.fg, bg = c.bg_visual },
    NeogitDiffContext = { bg = c.bg },
    NeogitDiffContextHighlight = { bg = c.bg_light },
    NeogitDiffAdd = { fg = c.git_add, bg = c.diff_add_bg },
    NeogitDiffAddHighlight = { fg = c.git_add, bg = "#2d5540" },
    NeogitDiffDelete = { fg = c.git_delete, bg = c.diff_delete_bg },
    NeogitDiffDeleteHighlight = { fg = c.git_delete, bg = "#552d30" },
    NeogitNotificationInfo = { fg = c.info },
    NeogitNotificationWarning = { fg = c.warning },
    NeogitNotificationError = { fg = c.error },
    NeogitCommitViewHeader = { fg = c.blue, bg = c.bg_highlight, bold = true },
    NeogitFilePath = { fg = c.blue },
    NeogitFold = { fg = c.gray_dark },
    NeogitGraphAuthor = { fg = c.orange },
    NeogitGraphRed = { fg = c.red },
    NeogitGraphWhite = { fg = c.fg },
    NeogitGraphYellow = { fg = c.yellow },
    NeogitGraphGreen = { fg = c.green },
    NeogitGraphCyan = { fg = c.cyan },
    NeogitGraphBlue = { fg = c.blue },
    NeogitGraphPurple = { fg = c.purple },
    NeogitGraphGray = { fg = c.gray },
    NeogitGraphOrange = { fg = c.orange },
    NeogitGraphBoldRed = { fg = c.red, bold = true },
    NeogitGraphBoldWhite = { fg = c.fg, bold = true },
    NeogitGraphBoldYellow = { fg = c.yellow, bold = true },
    NeogitGraphBoldGreen = { fg = c.green, bold = true },
    NeogitGraphBoldCyan = { fg = c.cyan, bold = true },
    NeogitGraphBoldBlue = { fg = c.blue, bold = true },
    NeogitGraphBoldPurple = { fg = c.purple, bold = true },
    NeogitGraphBoldGray = { fg = c.gray, bold = true },
    NeogitSignatureGood = { fg = c.green },
    NeogitSignatureBad = { fg = c.red },
    NeogitSignatureMissing = { fg = c.warning },
    NeogitSignatureNone = { fg = c.gray },
    NeogitSignatureGoodUnknown = { fg = c.aqua },
    NeogitSignatureGoodExpired = { fg = c.yellow },
    NeogitSignatureGoodExpiredKey = { fg = c.yellow },
    NeogitSignatureGoodRevokedKey = { fg = c.red },
    NeogitCherryPick = { fg = c.purple },
    NeogitRevert = { fg = c.red },
    NeogitSectionHeader = { fg = c.purple, bold = true },
    NeogitUntrackedfiles = { fg = c.git_untracked },
    NeogitUnstagedchanges = { fg = c.git_change },
    NeogitUnmergedchanges = { fg = c.git_conflict },
    NeogitUnpulledchanges = { fg = c.blue },
    NeogitRecentcommits = { fg = c.fg },
    NeogitStagedchanges = { fg = c.green },
    NeogitStashes = { fg = c.purple },
    NeogitRebasing = { fg = c.orange },

    -- Octo
    OctoEditable = { bg = c.bg_light },
    OctoBubble = { fg = c.fg, bg = c.bg_highlight },
    OctoGreen = { fg = c.green },
    OctoRed = { fg = c.red },
    OctoPurple = { fg = c.purple },
    OctoYellow = { fg = c.yellow },
    OctoBlue = { fg = c.blue },
    OctoGrey = { fg = c.gray },

    -- Copilot / Codeium
    CopilotSuggestion = { fg = c.gray_dark, italic = true },
    CopilotAnnotation = { fg = c.gray_dark, italic = true },
    CodeiumSuggestion = { fg = c.gray_dark, italic = true },

    -- Spectre
    SpectreHeader = { fg = c.purple, bold = true },
    SpectreBody = { fg = c.fg },
    SpectreFile = { fg = c.blue },
    SpectreDir = { fg = c.gray },
    SpectreSearch = { fg = c.bg, bg = c.red },
    SpectreBorder = { fg = c.border_light },
    SpectreReplace = { fg = c.bg, bg = c.green },

    -- Scrollbar
    ScrollbarHandle = { bg = c.bg_highlight },
    ScrollbarSearchHandle = { fg = c.yellow, bg = c.bg_highlight },
    ScrollbarSearch = { fg = c.yellow },
    ScrollbarErrorHandle = { fg = c.error, bg = c.bg_highlight },
    ScrollbarError = { fg = c.error },
    ScrollbarWarnHandle = { fg = c.warning, bg = c.bg_highlight },
    ScrollbarWarn = { fg = c.warning },
    ScrollbarInfoHandle = { fg = c.info, bg = c.bg_highlight },
    ScrollbarInfo = { fg = c.info },
    ScrollbarHintHandle = { fg = c.hint, bg = c.bg_highlight },
    ScrollbarHint = { fg = c.hint },
    ScrollbarMiscHandle = { fg = c.purple, bg = c.bg_highlight },
    ScrollbarMisc = { fg = c.purple },
    ScrollbarGitAdd = { fg = c.git_add },
    ScrollbarGitChange = { fg = c.aqua },
    ScrollbarGitDelete = { fg = c.git_delete },

    -- Overseer
    OverseerPENDING = { fg = c.gray },
    OverseerRUNNING = { fg = c.blue },
    OverseerSUCCESS = { fg = c.green },
    OverseerCANCELED = { fg = c.yellow },
    OverseerFAILURE = { fg = c.red },
    OverseerTask = { fg = c.fg },
    OverseerTaskBorder = { fg = c.border_light },
    OverseerOutput = { fg = c.fg },
    OverseerComponent = { fg = c.purple },
    OverseerField = { fg = c.cyan },

    -- render-markdown
    RenderMarkdownH1Bg = { bg = "#252a35" },
    RenderMarkdownH2Bg = { bg = "#252530" },
    RenderMarkdownH3Bg = { bg = "#252830" },
    RenderMarkdownH4Bg = { bg = "#2a2530" },
    RenderMarkdownH5Bg = { bg = "#2a2a30" },
    RenderMarkdownH6Bg = { bg = "#252a2a" },
    RenderMarkdownCode = { bg = c.bg_light },
    RenderMarkdownCodeInline = { bg = c.bg_light },
    RenderMarkdownBullet = { fg = c.blue },
    RenderMarkdownQuote = { fg = c.gray, italic = true },
    RenderMarkdownDash = { fg = c.border_light },
    RenderMarkdownLink = { fg = c.link, underline = true },
    RenderMarkdownSign = { fg = c.gray },
    RenderMarkdownMath = { fg = c.blue },
    RenderMarkdownWikiLink = { fg = c.purple, underline = true },
    RenderMarkdownUnchecked = { fg = c.gray },
    RenderMarkdownChecked = { fg = c.green },
    RenderMarkdownTableHead = { fg = c.blue, bold = true },
    RenderMarkdownTableRow = { fg = c.fg },
    RenderMarkdownTableFill = { fg = c.gray_dark },
    RenderMarkdownSuccess = { fg = c.green },
    RenderMarkdownInfo = { fg = c.info },
    RenderMarkdownHint = { fg = c.hint },
    RenderMarkdownWarn = { fg = c.warning },
    RenderMarkdownError = { fg = c.error },
  }
end

return M
